FROM ges-umap:local

WORKDIR /app

COPY requirements.txt /app/

RUN apt-get update && apt-get install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
